/****************************************************************************************/
/*  D3D12SHADERS.CPP                                                                    */
/*                                                                                      */
/*  Shader bytecode for the DirectX 12 driver (see D3D12Shaders.h).                     */
/****************************************************************************************/
#include <cstdio>
#include <cstring>
#include <vector>

#include <windows.h>
#include <d3dcompiler.h>
#include <wrl/client.h>

#include "D3D12Shaders.h"
#include "D3D12Config.h"
#include "D3D12Resource.h"
#include "D3D12Log.h"

// DXIL generated by the G3DCompileShaders build step (Direct3D12Driver.vcxproj).
#include "Shaders/g_TLPoly_VSMain.h"
#include "Shaders/g_TLPoly_PSGouraud.h"
#include "Shaders/g_TLPoly_PSTexture.h"
#include "Shaders/g_TLPoly_PSMultiTexture.h"
#include "Shaders/g_Present_VSFullscreen.h"
#include "Shaders/g_Present_PSPresent.h"

using Microsoft::WRL::ComPtr;

namespace
{
	struct ShaderDesc
	{
		const char*				File;			// under Shaders\ (and [Shaders] SourceDir)
		int						ResourceId;		// embedded source
		const char*				Entry;
		const char*				RuntimeTarget;	// D3DCompile profile for the fallback
		const unsigned char*	Dxil;
		SIZE_T					DxilSize;
	};

	const ShaderDesc Shaders[SHADER_COUNT] =
	{
		{ "TLPoly.hlsl", IDR_SHADER_TLPOLY, "VSMain",         "vs_5_0", g_TLPoly_VSMain,         sizeof(g_TLPoly_VSMain) },
		{ "TLPoly.hlsl", IDR_SHADER_TLPOLY, "PSGouraud",      "ps_5_0", g_TLPoly_PSGouraud,      sizeof(g_TLPoly_PSGouraud) },
		{ "TLPoly.hlsl", IDR_SHADER_TLPOLY, "PSTexture",      "ps_5_0", g_TLPoly_PSTexture,      sizeof(g_TLPoly_PSTexture) },
		{ "TLPoly.hlsl", IDR_SHADER_TLPOLY, "PSMultiTexture", "ps_5_0", g_TLPoly_PSMultiTexture, sizeof(g_TLPoly_PSMultiTexture) },
		{ "Present.hlsl", IDR_SHADER_PRESENT, "VSFullscreen", "vs_5_0", g_Present_VSFullscreen, sizeof(g_Present_VSFullscreen) },
		{ "Present.hlsl", IDR_SHADER_PRESENT, "PSPresent",    "ps_5_0", g_Present_PSPresent,    sizeof(g_Present_PSPresent) },
	};

	ComPtr<ID3DBlob>		Compiled[SHADER_COUNT];
	D3D12_SHADER_BYTECODE	Bytecode[SHADER_COUNT];

	bool DeviceSupportsSM6(ID3D12Device* Device)
	{
		D3D12_FEATURE_DATA_SHADER_MODEL Model = { D3D_SHADER_MODEL_6_0 };
		return SUCCEEDED(Device->CheckFeatureSupport(D3D12_FEATURE_SHADER_MODEL, &Model, sizeof(Model))) &&
			Model.HighestShaderModel >= D3D_SHADER_MODEL_6_0;
	}

	bool ReadFileText(const char* Path, std::vector<char>& Out)
	{
		FILE* File = nullptr;
		if (fopen_s(&File, Path, "rb") != 0 || !File)
			return false;
		fseek(File, 0, SEEK_END);
		const long Size = ftell(File);
		fseek(File, 0, SEEK_SET);
		Out.resize(Size > 0 ? static_cast<size_t>(Size) : 0);
		const bool Ok = Size >= 0 && fread(Out.data(), 1, Out.size(), File) == Out.size();
		fclose(File);
		return Ok;
	}

	bool ReadResourceText(int ResourceId, std::vector<char>& Out)
	{
		HMODULE Module = D3D12Config_Module();
		HRSRC Resource = FindResourceA(Module, MAKEINTRESOURCEA(ResourceId), MAKEINTRESOURCEA(10) /* RT_RCDATA */);
		HGLOBAL Handle = Resource ? LoadResource(Module, Resource) : nullptr;
		const void* Data = Handle ? LockResource(Handle) : nullptr;
		if (!Data)
			return false;
		const DWORD Size = SizeofResource(Module, Resource);
		Out.assign(static_cast<const char*>(Data), static_cast<const char*>(Data) + Size);
		return true;
	}

	ComPtr<ID3DBlob> CompileSource(const std::vector<char>& Source, const char* Name, const ShaderDesc& Desc)
	{
		ComPtr<ID3DBlob> Shader;
		ComPtr<ID3DBlob> Errors;
		UINT Flags = D3DCOMPILE_ENABLE_STRICTNESS;
#ifdef _DEBUG
		Flags |= D3DCOMPILE_DEBUG | D3DCOMPILE_SKIP_OPTIMIZATION;
#else
		Flags |= D3DCOMPILE_OPTIMIZATION_LEVEL3;
#endif
		const HRESULT Hr = D3DCompile(
			Source.data(), Source.size(), Name, nullptr, nullptr,
			Desc.Entry, Desc.RuntimeTarget, Flags, 0, &Shader, &Errors);
		if (FAILED(Hr))
		{
			D3D12Log::GetPtr()->Printf(
				"ERROR: %s:%s compilation failed (0x%08X): %s",
				Name, Desc.Entry, Hr,
				Errors ? static_cast<const char*>(Errors->GetBufferPointer()) : "no compiler details");
			return nullptr;
		}
		return Shader;
	}
}

grBoolean D3D12Shaders_Load(ID3D12Device* Device)
{
	D3D12Shaders_Unload();
	if (!Device)
		return GR_FALSE;

	char SourceDir[MAX_PATH] = "";
	const bool bLooseSource = D3D12Config_GetString("Shaders", "SourceDir", SourceDir, sizeof(SourceDir));
	const bool bSM6 = DeviceSupportsSM6(Device);
	const bool bRuntime = bLooseSource || !bSM6 || D3D12Config_GetBool("Shaders", "RuntimeCompile", false);

	if (bLooseSource)
		D3D12Log::GetPtr()->Printf("Shaders: compiling from %s", SourceDir);
	else if (!bSM6)
		D3D12Log::GetPtr()->Printf("Shaders: device has no SM 6.0, compiling embedded source as SM 5.0");
	else if (bRuntime)
		D3D12Log::GetPtr()->Printf("Shaders: RuntimeCompile set, compiling embedded source as SM 5.0");
	else
		D3D12Log::GetPtr()->Printf("Shaders: using precompiled DXIL (SM 6.0)");

	for (int Id = 0; Id < SHADER_COUNT; ++Id)
	{
		const ShaderDesc& Desc = Shaders[Id];

		if (bRuntime)
		{
			std::vector<char> Source;
			char Path[MAX_PATH] = "";
			bool bHaveSource = false;

			if (bLooseSource)
			{
				char Relative[MAX_PATH];
				sprintf_s(Relative, "%s\\%s", SourceDir, Desc.File);
				D3D12Config_ResolvePath(Relative, Path, sizeof(Path));
				bHaveSource = ReadFileText(Path, Source);
				if (!bHaveSource)
					D3D12Log::GetPtr()->Printf("WARNING: Shaders: cannot read %s, using the embedded copy", Path);
			}
			if (!bHaveSource)
			{
				strcpy_s(Path, Desc.File);
				bHaveSource = ReadResourceText(Desc.ResourceId, Source);
			}

			if (bHaveSource)
				Compiled[Id] = CompileSource(Source, Path, Desc);

			if (Compiled[Id])
			{
				Bytecode[Id].pShaderBytecode = Compiled[Id]->GetBufferPointer();
				Bytecode[Id].BytecodeLength = Compiled[Id]->GetBufferSize();
				continue;
			}
			// DXIL still works on an SM 6.0 device, so an edit that does not compile
			// falls back to the shaders the driver was built with.
			if (!bSM6)
			{
				D3D12Shaders_Unload();
				return GR_FALSE;
			}
			D3D12Log::GetPtr()->Printf("WARNING: Shaders: using precompiled %s:%s", Desc.File, Desc.Entry);
		}

		Bytecode[Id].pShaderBytecode = Desc.Dxil;
		Bytecode[Id].BytecodeLength = Desc.DxilSize;
	}

	return GR_TRUE;
}

void D3D12Shaders_Unload()
{
	for (int Id = 0; Id < SHADER_COUNT; ++Id)
	{
		Compiled[Id].Reset();
		Bytecode[Id] = D3D12_SHADER_BYTECODE{};
	}
}

D3D12_SHADER_BYTECODE D3D12Shaders_Get(D3D12_SHADER_ID Id)
{
	if (Id < 0 || Id >= SHADER_COUNT)
		return D3D12_SHADER_BYTECODE{};
	return Bytecode[Id];
}
