/****************************************************************************************/
/*  D3D12SHADERS.CPP                                                                    */
/*                                                                                      */
/*  Shader bytecode for the DirectX 12 driver (see D3D12Shaders.h).                     */
/****************************************************************************************/
#include <cstdio>
#include <cstring>
#include <vector>

#include <windows.h>
#include <d3dcompiler.h>
#include <wrl/client.h>

#include "D3D12Shaders.h"
#include "D3D12Config.h"
#include "D3D12Resource.h"
#include "D3D12Log.h"

// DXIL generated by the G3DCompileShaders build step (Direct3D12Driver.vcxproj).
#include "Shaders/g_TLPoly_VSMain.h"
#include "Shaders/g_TLPoly_PSGouraud.h"
#include "Shaders/g_TLPoly_PSTexture.h"
#include "Shaders/g_TLPoly_PSMultiTexture.h"
#include "Shaders/g_TLPoly_PSGouraud_Bindless.h"
#include "Shaders/g_TLPoly_PSTexture_Bindless.h"
#include "Shaders/g_TLPoly_PSMultiTexture_Bindless.h"
#include "Shaders/g_World_VSWorld.h"
#include "Shaders/g_World_PSWorldTexture.h"
#include "Shaders/g_World_PSWorldMultiTexture.h"
#include "Shaders/g_World_VSMesh.h"
#include "Shaders/g_World_VSWorldPBR.h"
#include "Shaders/g_World_PSWorldPBR.h"
#include "Shaders/g_World_VSMeshPBR.h"
#include "Shaders/g_Present_VSFullscreen.h"
#include "Shaders/g_Present_PSPresent.h"
#include "Shaders/g_Shadow_VSShadow.h"
#include "Shaders/g_Cluster_CSClusterLights.h"
#include "Shaders/g_Post_VSPost.h"
#include "Shaders/g_Post_PSBloomDown.h"
#include "Shaders/g_Post_PSBloomUp.h"
#include "Shaders/g_Post_PSSSAO.h"
#include "Shaders/g_Post_PSSSAOBlur.h"
#include "Shaders/g_Post_PSComposite.h"
#include "Shaders/g_Post_CSHistogramClear.h"
#include "Shaders/g_Post_CSHistogram.h"
#include "Shaders/g_Post_CSExposure.h"

using Microsoft::WRL::ComPtr;

namespace
{
	struct ShaderDesc
	{
		const char*				File;			// under Shaders\ (and [Shaders] SourceDir)
		int						ResourceId;		// embedded source
		const char*				Entry;
		const char*				RuntimeTarget;	// D3DCompile profile for the fallback
		bool					Bindless;		// compiled with G3D_BINDLESS=1
		const unsigned char*	Dxil;
		SIZE_T					DxilSize;
	};

	// Bindless variants index a descriptor array, which needs SM 5.1 in the fallback.
	const ShaderDesc Shaders[SHADER_COUNT] =
	{
		{ "TLPoly.hlsl",  IDR_SHADER_TLPOLY,  "VSMain",         "vs_5_0", false, g_TLPoly_VSMain,                  sizeof(g_TLPoly_VSMain) },
		{ "TLPoly.hlsl",  IDR_SHADER_TLPOLY,  "PSGouraud",      "ps_5_0", false, g_TLPoly_PSGouraud,               sizeof(g_TLPoly_PSGouraud) },
		{ "TLPoly.hlsl",  IDR_SHADER_TLPOLY,  "PSTexture",      "ps_5_0", false, g_TLPoly_PSTexture,               sizeof(g_TLPoly_PSTexture) },
		{ "TLPoly.hlsl",  IDR_SHADER_TLPOLY,  "PSMultiTexture", "ps_5_0", false, g_TLPoly_PSMultiTexture,          sizeof(g_TLPoly_PSMultiTexture) },
		{ "TLPoly.hlsl",  IDR_SHADER_TLPOLY,  "PSGouraud",      "ps_5_1", true,  g_TLPoly_PSGouraud_Bindless,      sizeof(g_TLPoly_PSGouraud_Bindless) },
		{ "TLPoly.hlsl",  IDR_SHADER_TLPOLY,  "PSTexture",      "ps_5_1", true,  g_TLPoly_PSTexture_Bindless,      sizeof(g_TLPoly_PSTexture_Bindless) },
		{ "TLPoly.hlsl",  IDR_SHADER_TLPOLY,  "PSMultiTexture", "ps_5_1", true,  g_TLPoly_PSMultiTexture_Bindless, sizeof(g_TLPoly_PSMultiTexture_Bindless) },
		{ "World.hlsl",   IDR_SHADER_WORLD,   "VSWorld",             "vs_5_1", true,  g_World_VSWorld,             sizeof(g_World_VSWorld) },
		{ "World.hlsl",   IDR_SHADER_WORLD,   "PSWorldTexture",      "ps_5_1", true,  g_World_PSWorldTexture,      sizeof(g_World_PSWorldTexture) },
		{ "World.hlsl",   IDR_SHADER_WORLD,   "PSWorldMultiTexture", "ps_5_1", true,  g_World_PSWorldMultiTexture, sizeof(g_World_PSWorldMultiTexture) },
		{ "World.hlsl",   IDR_SHADER_WORLD,   "VSMesh",              "vs_5_1", true,  g_World_VSMesh,              sizeof(g_World_VSMesh) },
		{ "World.hlsl",   IDR_SHADER_WORLD,   "VSWorldPBR",          "vs_5_1", true,  g_World_VSWorldPBR,          sizeof(g_World_VSWorldPBR) },
		{ "World.hlsl",   IDR_SHADER_WORLD,   "PSWorldPBR",          "ps_5_1", true,  g_World_PSWorldPBR,          sizeof(g_World_PSWorldPBR) },
		{ "World.hlsl",   IDR_SHADER_WORLD,   "VSMeshPBR",           "vs_5_1", true,  g_World_VSMeshPBR,           sizeof(g_World_VSMeshPBR) },
		{ "Present.hlsl", IDR_SHADER_PRESENT, "VSFullscreen",   "vs_5_0", false, g_Present_VSFullscreen,           sizeof(g_Present_VSFullscreen) },
		{ "Present.hlsl", IDR_SHADER_PRESENT, "PSPresent",      "ps_5_0", false, g_Present_PSPresent,              sizeof(g_Present_PSPresent) },
		{ "Shadow.hlsl",  IDR_SHADER_SHADOW,  "VSShadow",           "vs_5_1", false, g_Shadow_VSShadow,           sizeof(g_Shadow_VSShadow) },
		{ "Cluster.hlsl", IDR_SHADER_CLUSTER, "CSClusterLights",    "cs_5_1", false, g_Cluster_CSClusterLights,   sizeof(g_Cluster_CSClusterLights) },
		{ "Post.hlsl",    IDR_SHADER_POST,    "VSPost",             "vs_5_1", true,  g_Post_VSPost,               sizeof(g_Post_VSPost) },
		{ "Post.hlsl",    IDR_SHADER_POST,    "PSBloomDown",        "ps_5_1", true,  g_Post_PSBloomDown,          sizeof(g_Post_PSBloomDown) },
		{ "Post.hlsl",    IDR_SHADER_POST,    "PSBloomUp",          "ps_5_1", true,  g_Post_PSBloomUp,            sizeof(g_Post_PSBloomUp) },
		{ "Post.hlsl",    IDR_SHADER_POST,    "PSSSAO",             "ps_5_1", true,  g_Post_PSSSAO,               sizeof(g_Post_PSSSAO) },
		{ "Post.hlsl",    IDR_SHADER_POST,    "PSSSAOBlur",         "ps_5_1", true,  g_Post_PSSSAOBlur,           sizeof(g_Post_PSSSAOBlur) },
		{ "Post.hlsl",    IDR_SHADER_POST,    "PSComposite",        "ps_5_1", true,  g_Post_PSComposite,          sizeof(g_Post_PSComposite) },
		{ "Post.hlsl",    IDR_SHADER_POST,    "CSHistogramClear",   "cs_5_1", true,  g_Post_CSHistogramClear,     sizeof(g_Post_CSHistogramClear) },
		{ "Post.hlsl",    IDR_SHADER_POST,    "CSHistogram",        "cs_5_1", true,  g_Post_CSHistogram,          sizeof(g_Post_CSHistogram) },
		{ "Post.hlsl",    IDR_SHADER_POST,    "CSExposure",         "cs_5_1", true,  g_Post_CSExposure,           sizeof(g_Post_CSExposure) },
	};

	ComPtr<ID3DBlob>		Compiled[SHADER_COUNT];
	D3D12_SHADER_BYTECODE	Bytecode[SHADER_COUNT];

	bool DeviceSupportsSM6(ID3D12Device* Device)
	{
		D3D12_FEATURE_DATA_SHADER_MODEL Model = { D3D_SHADER_MODEL_6_0 };
		return SUCCEEDED(Device->CheckFeatureSupport(D3D12_FEATURE_SHADER_MODEL, &Model, sizeof(Model))) &&
			Model.HighestShaderModel >= D3D_SHADER_MODEL_6_0;
	}

	bool ReadFileText(const char* Path, std::vector<char>& Out)
	{
		FILE* File = nullptr;
		if (fopen_s(&File, Path, "rb") != 0 || !File)
			return false;
		fseek(File, 0, SEEK_END);
		const long Size = ftell(File);
		fseek(File, 0, SEEK_SET);
		Out.resize(Size > 0 ? static_cast<size_t>(Size) : 0);
		const bool Ok = Size >= 0 && fread(Out.data(), 1, Out.size(), File) == Out.size();
		fclose(File);
		return Ok;
	}

	bool ReadResourceText(int ResourceId, std::vector<char>& Out)
	{
		HMODULE Module = D3D12Config_Module();
		HRSRC Resource = FindResourceA(Module, MAKEINTRESOURCEA(ResourceId), MAKEINTRESOURCEA(10) /* RT_RCDATA */);
		HGLOBAL Handle = Resource ? LoadResource(Module, Resource) : nullptr;
		const void* Data = Handle ? LockResource(Handle) : nullptr;
		if (!Data)
			return false;
		const DWORD Size = SizeofResource(Module, Resource);
		Out.assign(static_cast<const char*>(Data), static_cast<const char*>(Data) + Size);
		return true;
	}

	ComPtr<ID3DBlob> CompileSource(const std::vector<char>& Source, const char* Name, const ShaderDesc& Desc)
	{
		ComPtr<ID3DBlob> Shader;
		ComPtr<ID3DBlob> Errors;
		UINT Flags = D3DCOMPILE_ENABLE_STRICTNESS;
#ifdef _DEBUG
		Flags |= D3DCOMPILE_DEBUG | D3DCOMPILE_SKIP_OPTIMIZATION;
#else
		Flags |= D3DCOMPILE_OPTIMIZATION_LEVEL3;
#endif
		// The bindless shaders index the whole descriptor heap.
		if (Desc.Bindless)
			Flags |= D3DCOMPILE_ENABLE_UNBOUNDED_DESCRIPTOR_TABLES;
		const D3D_SHADER_MACRO Bindless[] = { { "G3D_BINDLESS", "1" }, { nullptr, nullptr } };
		const HRESULT Hr = D3DCompile(
			Source.data(), Source.size(), Name, Desc.Bindless ? Bindless : nullptr, nullptr,
			Desc.Entry, Desc.RuntimeTarget, Flags, 0, &Shader, &Errors);
		if (FAILED(Hr))
		{
			D3D12Log::GetPtr()->Printf(
				"ERROR: %s:%s compilation failed (0x%08X): %s",
				Name, Desc.Entry, Hr,
				Errors ? static_cast<const char*>(Errors->GetBufferPointer()) : "no compiler details");
			return nullptr;
		}
		return Shader;
	}
}

grBoolean D3D12Shaders_Load(ID3D12Device* Device)
{
	D3D12Shaders_Unload();
	if (!Device)
		return GR_FALSE;

	char SourceDir[MAX_PATH] = "";
	const bool bLooseSource = D3D12Config_GetString("Shaders", "SourceDir", SourceDir, sizeof(SourceDir));
	const bool bSM6 = DeviceSupportsSM6(Device);
	const bool bRuntime = bLooseSource || !bSM6 || D3D12Config_GetBool("Shaders", "RuntimeCompile", false);

	if (bLooseSource)
		D3D12Log::GetPtr()->Printf("Shaders: compiling from %s", SourceDir);
	else if (!bSM6)
		D3D12Log::GetPtr()->Printf("Shaders: device has no SM 6.0, compiling embedded source as SM 5.0");
	else if (bRuntime)
		D3D12Log::GetPtr()->Printf("Shaders: RuntimeCompile set, compiling embedded source as SM 5.0");
	else
		D3D12Log::GetPtr()->Printf("Shaders: using precompiled DXIL (SM 6.0)");

	for (int Id = 0; Id < SHADER_COUNT; ++Id)
	{
		const ShaderDesc& Desc = Shaders[Id];

		if (bRuntime)
		{
			std::vector<char> Source;
			char Path[MAX_PATH] = "";
			bool bHaveSource = false;

			if (bLooseSource)
			{
				char Relative[MAX_PATH];
				sprintf_s(Relative, "%s\\%s", SourceDir, Desc.File);
				D3D12Config_ResolvePath(Relative, Path, sizeof(Path));
				bHaveSource = ReadFileText(Path, Source);
				if (!bHaveSource)
					D3D12Log::GetPtr()->Printf("WARNING: Shaders: cannot read %s, using the embedded copy", Path);
			}
			if (!bHaveSource)
			{
				strcpy_s(Path, Desc.File);
				bHaveSource = ReadResourceText(Desc.ResourceId, Source);
			}

			if (bHaveSource)
				Compiled[Id] = CompileSource(Source, Path, Desc);

			if (Compiled[Id])
			{
				Bytecode[Id].pShaderBytecode = Compiled[Id]->GetBufferPointer();
				Bytecode[Id].BytecodeLength = Compiled[Id]->GetBufferSize();
				continue;
			}

			// A pipeline cannot mix DXBC and DXIL, so one failure means none of the
			// run-time shaders can be used. On an SM 6.0 device the shaders the driver
			// was built with still work (for example after a bad edit in SourceDir).
			D3D12Shaders_Unload();
			if (!bSM6)
				return GR_FALSE;
			D3D12Log::GetPtr()->Printf("WARNING: Shaders: run-time compile failed, using the precompiled DXIL for all shaders");
			for (int Each = 0; Each < SHADER_COUNT; ++Each)
			{
				Bytecode[Each].pShaderBytecode = Shaders[Each].Dxil;
				Bytecode[Each].BytecodeLength = Shaders[Each].DxilSize;
			}
			return GR_TRUE;
		}

		Bytecode[Id].pShaderBytecode = Desc.Dxil;
		Bytecode[Id].BytecodeLength = Desc.DxilSize;
	}

	return GR_TRUE;
}

void D3D12Shaders_Unload()
{
	for (int Id = 0; Id < SHADER_COUNT; ++Id)
	{
		Compiled[Id].Reset();
		Bytecode[Id] = D3D12_SHADER_BYTECODE{};
	}
}

D3D12_SHADER_BYTECODE D3D12Shaders_Get(D3D12_SHADER_ID Id)
{
	if (Id < 0 || Id >= SHADER_COUNT)
		return D3D12_SHADER_BYTECODE{};
	return Bytecode[Id];
}
