/****************************************************************************************/
/*  JEMODEL.H (Forwarding to GRMODEL.H)                                         */
/*                                                                                      */
/*  Genesis3D: Reborn Engine Interface                                                  */
/*                                                                                      */
/****************************************************************************************/
#ifndef JE_JEMODEL_H
#define JE_JEMODEL_H

#include "GRMODEL.H"

#endif // JE_JEMODEL_H
