/****************************************************************************************/
/*  JEWORLD.H (Forwarding to GRWORLD.H)                                         */
/*                                                                                      */
/*  Genesis3D: Reborn Engine Interface                                                  */
/*                                                                                      */
/****************************************************************************************/
#ifndef JE_JEWORLD_H
#define JE_JEWORLD_H

#include "GRWORLD.H"

#endif // JE_JEWORLD_H
